name: InfluxDB v2 Source
language: python
variables:
  - name: output
    inputType: OutputTopic
    description: Quix topic to publish data to
    required: true
  - name: INFLUXDB_URL
    inputType: FreeText
    description: URL of your InfluxDB v2 instance
    defaultValue: http://influx.bermad.io
    required: true
  - name: INFLUXDB_TOKEN
    inputType: Secret
    multiline: false
    description: InfluxDB v2 authentication token
    defaultValue: INFLUXDB_V2_TOKEN
    required: true
  - name: INFLUXDB_ORG
    inputType: FreeText
    multiline: false
    description: InfluxDB v2 organization name
    defaultValue: primary
    required: true
  - name: INFLUXDB_BUCKET
    inputType: FreeText
    multiline: false
    description: InfluxDB v2 bucket name to read from
    defaultValue: logs
    required: true
  - name: MEASUREMENT
    inputType: FreeText
    description: Measurement to filter
    defaultValue: '*'
  - name: START_TIME
    inputType: FreeText
    description: Start time for data query
    defaultValue: -7d
  - name: QUERY_INTERVAL_SECONDS
    inputType: FreeText
    description: Interval between queries in seconds
    defaultValue: 60
  - name: BATCH_SIZE
    inputType: FreeText
    description: Number of records to fetch per query
    defaultValue: 1000
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: starter-transformation
