name: InfluxDB v3 Sink
language: python
variables:
  - name: INPUT_TOPIC
    inputType: InputTopic
    multiline: false
    description: The input topic from which to consume the InfluxDB v2 data
    defaultValue: influxdbv2-data
  - name: INFLUXDB_HOST
    inputType: FreeText
    multiline: false
    description: The address of the InfluxDB v3 instance
    defaultValue: https://us-east-1-1.aws.cloud2.influxdata.com
    required: true
  - name: INFLUXDB_ORG
    inputType: FreeText
    multiline: false
    description: The configured organization in the InfluxDB v3 instance
    defaultValue: dev
    required: true
  - name: INFLUXDB_BUCKET
    inputType: FreeText
    multiline: false
    description: The name of the InfluxDB v3 bucket to store the synced data
    defaultValue: logs
  - name: INFLUXDB_TOKEN
    inputType: Secret
    multiline: false
    description: The configured API Token to access the InfluxDB v3 instance (defined as a secret in Quix)
    defaultValue: INFLUXDB_V3_TOKEN
    required: true
  - name: INFLUXDB_TAG_KEYS
    inputType: FreeText
    description: A list of tags to select when when writing the data to InfluxDB v3 (all others will be ignored)
  - name: INFLUXDB_FIELD_KEYS
    inputType: FreeText
    description: A list of fields to select when when writing the data to InfluxDB v3 (all others will be ignored)
    required: true
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
