name: influxdb-3.0-sink-new
language: python
variables:
  - name: input
    inputType: InputTopic
    multiline: false
    description: This is the input topic
    defaultValue: influxdbv2-data
    required: true
  - name: INFLUXDB_HOST
    inputType: FreeText
    description: Host address for the InfluxDB instance.
    defaultValue: https://us-east-1-1.aws.cloud2.influxdata.com
    required: true
  - name: INFLUXDB_TOKEN
    inputType: Secret
    description: Authentication token to access InfluxDB.
    defaultValue: INFLUXDB_V3_TOKEN
    required: true
  - name: INFLUXDB_ORG
    inputType: FreeText
    description: Organization name in InfluxDB.
    defaultValue: dev
  - name: INFLUXDB_DATABASE
    inputType: FreeText
    description: Database name in InfluxDB where data should be stored.
    defaultValue: logs
    required: true
  - name: INFLUXDB_TAG_KEYS
    inputType: FreeText
    description: 'The tags to include when writing the measurement data. Example: Tag1,Tag2'
    defaultValue: '["entity_id","entity_index","entity_name","id","line","name","sensor_name","serial","switch_name","type"]'
  - name: INFLUXDB_FIELD_KEYS
    inputType: FreeText
    description: 'The fields to include when writing the measurement data. Example: Field1,Field2'
    defaultValue: '["flow","flow_avg","flow_max","flow_min","flow_sp","index","latch_position","position","pressure_p1","pressure_p1_avg","pressure_p1_max","pressure_p1_min","pressure_p2","pressure_p2_avg","pressure_p2_max","pressure_p2_min","pressure_sp","v1_cycles","v2_cycles","v_bat","value","value_avg","value_curr","value_max","value_min","valve_position","volume","water_level","water_level_avg","water_level_max","water_level_min"]'
  - name: CONSUMER_GROUP_NAME
    inputType: FreeText
    description: The name of the consumer group to use when consuming from Kafka
    defaultValue: influxdb-sink
    required: true
  - name: TIMESTAMP_COLUMN
    inputType: FreeText
    description: 'The column containing the timestamp column. NOTE: Must be nanoseconds'
  - name: BUFFER_SIZE
    inputType: FreeText
    description: The number of records that sink holds before flush data to the InfluxDb
    defaultValue: 1000
  - name: INFLUXDB_BUCKET
    inputType: FreeText
    multiline: false
    description: The name of the InfluxDB v3 bucket to store the synced data
    defaultValue: logs
dockerfile: dockerfile
runEntryPoint: main.py
defaultFile: main.py
libraryItemId: influxdb-3-destination
